### ISSUE TITLE
User gets an error while trying to run a bundle 'selenium-webdriver-machine' from the 'emend-computer'

### ISSUE THREAD

**Issue by qaautotrain** [Traap/emend-computer#18]
Description : User gets an error while trying to run a bundle 'selenium-webdriver-machine' from the 'emend-computer'

Steps : Follow the document @  https://github.com/Traap/emend-computer/wiki/Selenium-WebDriver-Test-Machine

Command : emend --verbose --nodryrun -bundle=selenium-webdriver-machine

Error:
Parsing bundle/undle=selenium-webdriver-machine/undle=selenium-webdriver-machine.yaml
/var/lib/gems/2.3.0/gems/emend-1.1.7/lib/emend/workflow.rb:28:in `initialize': No such file or directory @ rb_sysopen - bundle/undle=selenium-webdriver-machine/undle=selenium-webdriver-machine.yaml (Errno::ENOENT)
        from /var/lib/gems/2.3.0/gems/emend-1.1.7/lib/emend/workflow.rb:28:in `open'
        from /var/lib/gems/2.3.0/gems/emend-1.1.7/lib/emend/workflow.rb:28:in `parse_yaml_file'
        from /var/lib/gems/2.3.0/gems/emend-1.1.7/lib/emend/workflow.rb:16:in `block in orchestrate'
        from /var/lib/gems/2.3.0/gems/emend-1.1.7/lib/emend/workflow.rb:15:in `each'
        from /var/lib/gems/2.3.0/gems/emend-1.1.7/lib/emend/workflow.rb:15:in `orchestrate'
        from /var/lib/gems/2.3.0/gems/emend-1.1.7/lib/emend.rb:24:in `execute'
        from /var/lib/gems/2.3.0/gems/emend-1.1.7/bin/emend:6:in `<top (required)>'
        from /usr/local/bin/emend:23:in `load'
        from /usr/local/bin/emend:23:in `<main>'

Note : Attached screen shots![bundle_error.PNG](https://images.zenhubusercontent.com/5a7a56784b5806bc2bc5dbfe/f2404bc7-6a04-44be-8f8b-d833f79e72f4)

**Comment by Traap** [comment]
Wiki page has been corrected.

**Comment by qaautotrain** [comment]
Change the command line from "emend --verbose --nodryrun -bundle=-selenium-webdriver-machine" to "emend --verbose --nodryrun --bundle=selenium-webdriver-machine" based on the instructions under README.md under emend-computer, "How to install a bundle" section. Tested on 2/8/18.
