### ISSUE TITLE
Add app for installing Chocolately

### ISSUE THREAD

**Issue by kthurow** [Traap/emend-computer#31]
According to the chocolately installation page (https://chocolatey.org/install), chocolately can be installed programmatically by running either of these two commands (as admin). The first command would be run from powershell, the second from cmd.exe. I believe this app is windows-only.

Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

**Comment by Traap** [comment]
See #33 for example use.
